name: fieldglass-connector
version: 0.1.0
description: "Enables the preview integration of SAP Fieldglass Events. It is not recommended for production scenarios."
id: facbbe92-0a84-16e3-ab17-d693be873g59
displayName: "[Preview] SAP Fieldglass - Event Connector"
tags: preview,fieldglass,connector
labels:
  preview: "true"
providerDisplayName: SAP
longDescription: "Integrates SAP Fieldglass in preview mode by registering its Events in an existing Application and enables consuming the Events from a lambda or microservice. It is not recommended for production use."
documentationURL: https://www.fieldglass.com/
bindable: false
provisionOnlyOnce: true
imageUrl: https://raw.githubusercontent.com/jcawley5/kyma_examples/master/fieldglassconnector/logos/fieldglass.jpg
