name: callidus-connector
version: 0.1.0
description: "Enables the preview integration of SAP Callidus Cloud. It is not recommended for production scenarios."
id: ef0cf2d7-f2ea-4f6f-b815-fdb73fe49bec
displayName: "[Preview] SAP Callidus Cloud Connector"
tags: preview,callidus,connector
labels:
  preview: "true"
providerDisplayName: SAP
longDescription: "Integrates SAP Callidus Cloud in preview mode by registering its APIs in an existing Application and enables consuming the APIs from a lambda or microservice. It is not recommended for production use."
documentationURL: https://docs.calliduscloud.com/
bindable: false
provisionOnlyOnce: true
imageUrl: https://raw.githubusercontent.com/jcawley5/kyma-connectors/master/logos/calliduscloud.png
